name: build-and-release-db
run-name: ${{ github.actor }} is compiling the sql file
on: 
  push:
    tags:
      - "v.*"

permissions:
  contents: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cat FluMutDB.sql | sqlite3 FluMutDB.sqlite3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: FluMutDB.sqlite3
