name: build-and-release-db
run-name: ${{ github.actor }} is compiling the sql file
on: 
  push:
    tags:
      - "v.*"

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cat FluMutDb5.sql | sqlite3 FluMutDb5.sqlite3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: FluMutDb5.sqlite3
