name: Create release and deploy FluMutDB
run-name: ${{ github.actor }} is releasing ${{ github.ref }}

on: 
  push:
    tags:
      - "v.*"


jobs:
  build:
    name: Build FluMutDB
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build SQLite DB
        run: |
          mkdir -p src/flumutdb/
          touch src/flumutdb/__init__.py
          cat flumut_db.sql | sqlite3 src/flumutdb/flumut_db.sqlite
          sqlite3 src/flumutdb/flumut_db.sqlite "SELECT major || '.' || minor FROM db_version" >version.txt
      - name: Upload sqlite DB
        uses: actions/upload-artifact@v4
        with:
          name: db
          path: src/flumutdb/flumut_db.sqlite
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build FluMutDB
        run: python -m build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error


  release:
    name: Create release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]

    steps:
      - name: Download db
        uses: actions/download-artifact@v4
        with:
          name: db
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            flumut_db.sqlite
            dist/*


  update_docs:
    name: Update FluMut documentation with new markers
    runs-on: ubuntu-latest
    needs: [release]
    environment: FluMutPagesTrigger

    steps:
      - name: variables
        run: |
          repo_owner="izsvenezie-virology" 
          repo_name="FluMut"  
          event_type="trigger-update-markers"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"


  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: pypi-release
    needs: release

    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
