name: Create release and deploy
run-name: ${{ github.actor }} is releasing ${{ github.ref }}
on: 
  push:
    tags:
      - "v.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  build-sqlite-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build SQLite DB
        run: |
          mkdir -p src/flumutdb/
          touch src/flumutdb/__init__.py
          cat flumut_db.sql | sqlite3 src/flumutdb/flumut_db.sqlite
          sqlite3 src/flumutdb/flumut_db.sqlite "SELECT major || '.' || minor FROM db_version" >version.txt

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist_folder
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            src/flumutdb/flumut_db.sqlite
            dist/*
